name: Download

on:
  workflow_dispatch:
    inputs:
      weekday:
        description: 'weekday'
        required: false
        default: ''

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip3 install yt-dlp yt-dlp-rajiko

      - name:　Build and Download
        run: cargo run -- ${{ github.event.inputs.weekday }}

      - name: Collect
        run: |
          mkdir -p radiko
          mv *.m4a radiko/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: radiko/
